export const APP_VERSION='2.12.21'
export const APP_NAME='ATLAS'
export const APP_LONG_NAME='ATLAS TRADING INTELLIGENCE'
export const APP_ENGINE_NAME='ORT ENGINE'
export const APP_BUILD_LABEL=`ATLAS V${APP_VERSION} LIVE OPERATIONAL · MOTOR ORT`
